import React from 'react';
import './DiseaseDetection.css';

/**
 * DiseaseDetection Page Component
 * 
 * Demonstrates:
 * - Clean, professional agriculture diagnostics user interface
 * - Component composition with feature cards, workflow steps, and photography guides
 */
function DiseaseDetection() {
  // 4 Steps: How CropVision Will Help
  const plannedSteps = [
    {
      stepNumber: '01',
      icon: '📸',
      title: 'Upload Crop Image',
      description: 'Capture or upload a clear photo of an infected leaf or affected foliage using your smartphone or computer.',
    },
    {
      stepNumber: '02',
      icon: '🧠',
      title: 'Analyze Crop Health',
      description: 'The intelligent vision model scans visual symptoms, discoloration patterns, and lesion geometries.',
    },
    {
      stepNumber: '03',
      icon: '🔬',
      title: 'Identify Possible Disease',
      description: 'The system classifies the specific crop pathogen (fungal, bacterial, or viral) with an accuracy confidence score.',
    },
    {
      stepNumber: '04',
      icon: '💊',
      title: 'Get Farming Recommendations',
      description: 'Receive verified dual organic remedies and chemical treatment steps to protect crop yield.',
    },
  ];

  // 4 Analysis Capability Feature Cards
  const analysisFeatureCards = [
    {
      icon: '🌱',
      badge: 'Metric 1',
      title: 'Crop Health Status',
      description: 'Visual health index indicating the overall physiological condition and severity stage of the plant.',
      exampleOutput: 'e.g. Early Stage Foliar Blight detected with 85% healthy surrounding tissue.',
    },
    {
      icon: '🔬',
      badge: 'Metric 2',
      title: 'Disease Identification',
      description: 'Precise classification of the pathogen name, scientific taxonomy, and affected host crop species.',
      exampleOutput: 'e.g. Leaf Spot (Alternaria solani) identified on Tomato foliage.',
    },
    {
      icon: '📊',
      badge: 'Metric 3',
      title: 'Confidence Score',
      description: 'Statistical probability score generated by the trained neural network validating diagnostic reliability.',
      exampleOutput: 'e.g. 92.4% prediction certainty based on validated plant pathology dataset.',
    },
    {
      icon: '🛡️',
      badge: 'Metric 4',
      title: 'Recommended Action',
      description: 'Curated agricultural guidance providing immediate organic bio-control and chemical fungicide solutions.',
      exampleOutput: 'e.g. Neem oil foliar spray (5ml/L) & maintain 45cm plant spacing.',
    },
  ];

  return (
    <div className="disease-detection-page page-wrapper">
      <div className="container">
        {/* ===================================================================
            1. PAGE HEADER
            =================================================================== */}
        <header className="page-header text-center">
          <span className="badge page-badge">AI Diagnostic Interface</span>
          <h1 className="page-title">Crop Disease Detection</h1>
          <p className="page-description">
            Explore how CropVision will help identify crop health issues and provide useful farming insights.
          </p>
        </header>

        {/* ===================================================================
            2. UPLOAD WORKSPACE AREA
            =================================================================== */}
        <section className="card upload-workspace-card" aria-label="Upload interface">
          <div className="static-upload-dropzone">
            <div className="upload-icon-circle">
              <span className="upload-icon" role="img" aria-label="Camera icon">
                📷
              </span>
            </div>

            <h2 className="upload-heading">Upload Crop Image</h2>
            <p className="upload-instruction text-muted">
              Upload a clear image of a crop leaf to analyze its health.
            </p>

            <div className="format-indicator">
              <span className="badge badge-neutral">JPG, PNG or JPEG</span>
            </div>

            {/* Visual Action Buttons */}
            <div className="upload-buttons-container">
              <button
                type="button"
                className="btn btn-secondary btn-lg static-choose-btn"
              >
                📁 Choose Image
              </button>

              <button
                type="button"
                className="btn btn-primary btn-lg static-analyze-btn"
              >
                Analyze Crop 🔬
              </button>
            </div>
          </div>
        </section>

        {/* ===================================================================
            3. HOW IT WILL WORK (4 Step Process)
            =================================================================== */}
        <section className="section how-it-works-section">
          <div className="section-header text-center">
            <span className="badge page-badge">Operational Workflow</span>
            <h2 className="section-title">How CropVision Will Help</h2>
            <p className="section-subtitle">
              A streamlined four-step diagnosis process designed to make precision plant pathology accessible to every grower.
            </p>
          </div>

          <div className="grid-4">
            {plannedSteps.map((step) => (
              <div key={step.stepNumber} className="card step-card">
                <span className="step-number">{step.stepNumber}</span>
                <span className="step-icon" role="img" aria-label={step.title}>
                  {step.icon}
                </span>
                <h3 className="step-title">{step.title}</h3>
                <p className="step-description text-muted text-sm">{step.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ===================================================================
            4. PLANNED ANALYSIS FEATURES
            =================================================================== */}
        <section className="section planned-features-section" style={{ paddingTop: 0 }}>
          <div className="section-header text-center">
            <span className="badge page-badge">Diagnostic Capabilities</span>
            <h2 className="section-title">Planned Analysis Features</h2>
            <p className="section-subtitle">
              Key health indicators and diagnostic data points our crop analysis model generates upon full diagnostic evaluation.
            </p>
          </div>

          <div className="grid-2 preview-features-grid">
            {analysisFeatureCards.map((feat, index) => (
              <div key={index} className="card preview-feature-card">
                <div className="feature-card-top flex flex-between">
                  <div className="feature-icon-badge">
                    <span role="img" aria-label={feat.title}>{feat.icon}</span>
                  </div>
                  <span className="badge badge-neutral text-xs">{feat.badge}</span>
                </div>

                <h3 className="preview-feature-title">{feat.title}</h3>
                <p className="preview-feature-desc text-muted text-sm">{feat.description}</p>

                <div className="preview-spec-box">
                  <span className="spec-label text-xs">Example Output:</span>
                  <p className="spec-detail text-sm">{feat.exampleOutput}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ===================================================================
            5. PHOTO GUIDELINES SECTION
            =================================================================== */}
        <section className="section" style={{ paddingTop: 0 }}>
          <div className="card photo-guide-card">
            <div className="guide-header">
              <span className="guide-icon" role="img" aria-label="Guidelines">📋</span>
              <div>
                <h3 className="guide-title">Scanning Guidelines</h3>
                <p className="text-muted text-sm">
                  Recommended standards for capturing clear leaf photography for maximum diagnostic accuracy.
                </p>
              </div>
            </div>

            <div className="grid-3 guide-grid">
              <div className="guide-col">
                <strong className="guide-point-title">☀️ Natural Lighting</strong>
                <p className="text-muted text-xs">
                  Capture foliage in bright, even daylight. Avoid extreme shadows or harsh flash glare.
                </p>
              </div>

              <div className="guide-col">
                <strong className="guide-point-title">🔍 Close-Up Focus</strong>
                <p className="text-muted text-xs">
                  Keep the camera 10–15 cm from the infected leaf, ensuring sharp focus on spots or lesions.
                </p>
              </div>

              <div className="guide-col">
                <strong className="guide-point-title">🍃 Single Leaf View</strong>
                <p className="text-muted text-xs">
                  Frame a single affected leaf against a neutral background to prevent background clutter.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export default DiseaseDetection;
